@echo off
echo Fixing Claude Code memory leak...
echo Killing WSL processes...
wsl --shutdown
timeout /t 2
echo Cleaning memory...
powershell -Command "Get-Service LxssManager | Restart-Service"
timeout /t 3
echo Starting WSL...
wsl -d Ubuntu -e echo "WSL restarted - Claude Code memory leak cleaned"
echo Ready to use Claude Code again!