#!/bin/bash
# Display help for testing commands

echo "🧪 WorldArchitect.AI Testing Modes"
echo ""
echo "Available Commands:"
echo "  /teste    - Mock mode (fast, free, isolated)"
echo "  /tester   - Real mode (uses actual services, costs money)"
echo "  /testerc  - Capture mode (real services + data capture)"
echo ""
echo "Setup for Real/Capture Modes:"
echo "  export TEST_GEMINI_API_KEY=your_api_key"
echo "  export TEST_FIRESTORE_PROJECT=your_test_project  # optional"
echo ""
echo "Examples:"
echo "  /teste                    # All tests, mock mode"
echo "  /teste test_user          # Specific tests, mock mode"
echo "  /tester                   # All tests, real services"
echo "  /testerc test_campaign    # Specific tests, real + capture"
echo ""
echo "Cost Estimates:"
echo "  Mock Mode:    $0"
echo "  Real Mode:    ~$0.10-$1.00 per full test run"
echo "  Capture Mode: ~$0.10-$1.00 per run + storage"
echo ""
echo "Test Modes (Real-Mode Testing Framework):"
echo "  TEST_MODE=mock     - MockServiceProvider (default)"
echo "  TEST_MODE=real     - RealServiceProvider"
echo "  TEST_MODE=capture  - RealServiceProvider with data capture"
echo ""
echo "Integration with existing scripts:"
echo "  ./run_tests.sh         - Honors TEST_MODE environment variable"
echo "  ./run_ui_tests.sh      - Honors TEST_MODE environment variable"
echo "  ./run_e2e_tests.sh     - Enhanced e2e runner with TEST_MODE support"
